### ISSUE TITLE
Zero help radius should not be allowed

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.mutualaid#14]
Currently you can enter a help radius of 0.

**Comment by jensschuppe** [comment]
This may be desirable if you're providing help for people at the same address. But fair point, you'd just knock your neighbours' doors if that's what you want.

Is there a technical issue with having a `0` help radius, i.e. how's it technically different to someone entering `1 meter`? It feels like this would only help to reduce spam submissions, since somebody aiming to help people would not try to trick the system.

**Comment by bjendres** [comment]
You're right. We'll close this, also seeing that the report (#15) would pick it up
